// MPEG-2 transport stream constants (ISO/IEC 13818-1).
export const PACKET_SIZE = 188;
export const SYNC_BYTE = 0x47;
export const MAX_STREAM_SIZE = 8 * 1024 * 1024; // 8 MiB
export const NULL_PID = 0x1fff;
export const PID_PAT = 0x0000;

export const TABLE_ID_PAT = 0x00;
export const TABLE_ID_PMT = 0x02;

// PCR counts in units of a 27 MHz clock; the 33-bit PCR_base wraps at 2^33.
export const PCR_BASE_WRAP = 2 ** 33;
export const PCR_TICKS_PER_MS = 27000;

// Stable error codes returned to API clients. Do not rename.
export const ERROR_CODES = {
  EMPTY_STREAM: 'EMPTY_STREAM',
  BODY_TOO_LARGE: 'BODY_TOO_LARGE',
  PACKET_LENGTH: 'PACKET_LENGTH',
  INVALID_SYNC_BYTE: 'INVALID_SYNC_BYTE',
  TRANSPORT_ERROR_INDICATOR: 'TRANSPORT_ERROR_INDICATOR',
  SCRAMBLED: 'SCRAMBLED',
  DISCONTINUITY_FLAG: 'DISCONTINUITY_FLAG',
  ADAPTATION_FIELD_INVALID: 'ADAPTATION_FIELD_INVALID',
  NO_PAT: 'NO_PAT',
  NO_PMT: 'NO_PMT',
  MULTIPLE_PROGRAMS: 'MULTIPLE_PROGRAMS',
  SECTION_INVALID: 'SECTION_INVALID',
  SECTION_NOT_SINGLE_PACKET: 'SECTION_NOT_SINGLE_PACKET',
  SECTION_CRC_FAILED: 'SECTION_CRC_FAILED',
  TABLE_VERSION_CONTENT_MISMATCH: 'TABLE_VERSION_CONTENT_MISMATCH',
  PMT_PROGRAM_MISMATCH: 'PMT_PROGRAM_MISMATCH',
  CONTINUITY_ERROR: 'CONTINUITY_ERROR',
  PCR_WRONG_PID: 'PCR_WRONG_PID',
  PCR_INVALID: 'PCR_INVALID',
  PCR_MISSING: 'PCR_MISSING',
  PCR_BACKWARD: 'PCR_BACKWARD',
  PCR_GAP_EXCEEDED: 'PCR_GAP_EXCEEDED',
};
